spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/book_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://db:3306/book_management?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: book-management-system

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: true

logging:
  level:
    org.springframework: WARN
    com.example.Book.Management: INFO

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: bookmanagement


